# Generated by Django 4.2.3 on 2023-07-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('bank_id', models.CharField(max_length=250)),
                ('District', models.CharField(max_length=250)),
                ('IFSC_code', models.CharField(max_length=100)),
            ],
        ),
    ]
