# Generated by Django 4.2.3 on 2023-07-27 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branches',
            old_name='name',
            new_name='br_name',
        ),
    ]
