# Generated by Django 4.2.3 on 2023-07-28 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankApp', '0003_remove_branches_bank_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('br_name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('District', models.CharField(max_length=250)),
                ('IFSC_code', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'branch',
                'verbose_name_plural': 'branches',
                'ordering': ('br_name',),
            },
        ),
        migrations.CreateModel(
            name='Sub_branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('br_name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('IFSC_code', models.CharField(max_length=250)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankApp.branch')),
            ],
            options={
                'verbose_name': 'sub_branch',
                'verbose_name_plural': 'sub_branches',
                'ordering': ('br_name',),
            },
        ),
        migrations.DeleteModel(
            name='Branches',
        ),
    ]
