# Generated by Django 4.2.3 on 2023-07-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=250)),
                ('Ph_no', models.IntegerField()),
                ('mail_id', models.CharField(max_length=250)),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=250)),
                ('branch', models.CharField(max_length=250)),
                ('ac_type', models.CharField(max_length=250)),
                ('materials', models.CharField(max_length=250)),
            ],
        ),
    ]
